// menu.js
// COMPLETE DATABASE (Columns 1, 2, and 3)
// ---------------------------------------------------------

const menuItems = [
    // ===========================
    // COLUMN 1: SNACKS & BASICS
    // ===========================
    { id: 1, name: "Tea", price: 20, category: "beverages", image: "☕" },
    { id: 2, name: "Coffee", price: 30, category: "beverages", image: "☕" },
    { id: 3, name: "Puff", price: 30, category: "snacks", image: "🥐" },
    { id: 4, name: "Poha", price: 30, category: "snacks", image: "🥣" },
    { id: 5, name: "Samosa (1 Pc.)", price: 20, category: "snacks", image: "🥟" },
    { id: 6, name: "Kachori (1 Pc.)", price: 30, category: "snacks", image: "🥯" },
    { id: 7, name: "Bread Pakoda (1 Pc.)", price: 30, category: "snacks", image: "🍞" },
    { id: 8, name: "Vadapav", price: 30, category: "snacks", image: "🍔" },
    { id: 9, name: "Vadapav Butter", price: 45, category: "snacks", image: "🧈" },
    { id: 10, name: "Vadapav Cheese", price: 55, category: "snacks", image: "🧀" },
    { id: 11, name: "Bread Butter / Muska Bun", price: 35, category: "snacks", image: "🥯" },
    { id: 12, name: "Bread Butter Jam", price: 40, category: "snacks", image: "🍓" },
    { id: 13, name: "Vegetable Sandwich", price: 50, category: "sandwiches", image: "🥪" },
    { id: 14, name: "Veg Grill Sandwich", price: 60, category: "sandwiches", image: "🥪" },
    { id: 15, name: "Veg Cheese Grill Sw", price: 75, category: "sandwiches", image: "🧀" },
    { id: 16, name: "Cheese Chilly Grill Sw", price: 90, category: "sandwiches", image: "🌶️" },
    { id: 17, name: "Club Sandwich", price: 100, category: "sandwiches", image: "🥪" },
    { id: 18, name: "Maggi", price: 55, category: "maggi", image: "🍜" },
    { id: 19, name: "Veg Burger", price: 75, category: "fastfood", image: "🍔" },
    { id: 20, name: "Cheese Burger", price: 90, category: "fastfood", image: "🍔" },
    { id: 21, name: "Pizza", price: 120, category: "fastfood", image: "🍕" },
    { id: 22, name: "French Fries & Other", price: 75, category: "fastfood", image: "🍟" },
    { id: 23, name: "Veg Wrap", price: 120, category: "wraps", image: "🌯" },
    { id: 24, name: "Paneer Wrap", price: 140, category: "wraps", image: "🌯" },
    { id: 25, name: "Cheese Wrap", price: 150, category: "wraps", image: "🌯" },
    { id: 26, name: "Bhel", price: 50, category: "chat", image: "🥣" },
    { id: 27, name: "Sevpuri", price: 80, category: "chat", image: "🥣" },
    { id: 28, name: "Dahipuri", price: 90, category: "chat", image: "🥣" },
    { id: 29, name: "Aloo Tikki", price: 90, category: "chat", image: "🥔" },
    { id: 30, name: "Aloo Tikki Chhole", price: 100, category: "chat", image: "🥘" },
    { id: 31, name: "Samosa Chhole Chat", price: 100, category: "chat", image: "🥟" },
    { id: 32, name: "Dahi Papdi Chat", price: 90, category: "chat", image: "🥣" },
    { id: 33, name: "Corn Chat", price: 45, category: "chat", image: "🌽" },

    // ===========================
    // COLUMN 2: MEALS & SOUTH INDIAN
    // ===========================
    { id: 34, name: "Chhole Bhature", price: 100, category: "meals", image: "🍛" },
    { id: 35, name: "Muttera Kulche", price: 100, category: "meals", image: "🥘" },
    { id: 36, name: "Pav Bhaji Butter", price: 100, category: "meals", image: "🍲" },
    { id: 37, name: "Veg Stuff Paratha With Curd", price: 75, category: "meals", image: "🥞" },
    { id: 38, name: "Paneer Paratha With Curd", price: 90, category: "meals", image: "🥞" },
    { id: 39, name: "Cheese Paratha With Curd", price: 110, category: "meals", image: "🧀" },
    { id: 40, name: "Mini Meals", price: 80, category: "meals", image: "🍱" },
    { id: 41, name: "Gulab Jamun/Rasgulla", price: 25, category: "sweets", image: "🍬" },
    { id: 42, name: "Upma", price: 35, category: "south_indian", image: "🥣" },
    { id: 43, name: "Idli Sambhar", price: 50, category: "south_indian", image: "🍲" },
    { id: 44, name: "Tatta Idli", price: 70, category: "south_indian", image: "⚪" },
    { id: 45, name: "Idli Chutney", price: 40, category: "south_indian", image: "🥥" },
    { id: 46, name: "Masala Dosa", price: 80, category: "south_indian", image: "🥞" },
    { id: 47, name: "Mysore Masala Dosa", price: 90, category: "south_indian", image: "🌶️" },
    { id: 48, name: "Cheese Masala Dosa", price: 110, category: "south_indian", image: "🧀" },
    { id: 49, name: "Veg Uttapam", price: 80, category: "south_indian", image: "🍕" },
    { id: 50, name: "Curd Rice", price: 80, category: "south_indian", image: "🍚" },
    { id: 51, name: "Veg Manchurian", price: 100, category: "chinese", image: "🧆" },
    { id: 52, name: "Paneer Chilly", price: 135, category: "chinese", image: "🌶️" },
    { id: 53, name: "Noodles", price: 100, category: "chinese", image: "🍜" },
    { id: 54, name: "Fried Rice", price: 100, category: "chinese", image: "🍚" },
    { id: 55, name: "Spring Roll", price: 110, category: "chinese", image: "🌯" },
    { id: 56, name: "Chinese Bhel", price: 120, category: "chinese", image: "🍜" },
    { id: 57, name: "Chinese Combos", price: 110, category: "chinese", image: "🍱" },

    // ===========================
    // COLUMN 3: SHAKES, ITALIAN & DESSERTS
    // ===========================
    { id: 58, name: "Bean To Coffee", price: 60, category: "beverages", image: "☕" },
    { id: 59, name: "Hot Chocolate", price: 90, category: "beverages", image: "🍫" },
    { id: 60, name: "Buttermilk", price: 30, category: "beverages", image: "🥛" },
    { id: 61, name: "Lassi", price: 50, category: "beverages", image: "🥛" },
    { id: 62, name: "Nimbu Pani", price: 25, category: "beverages", image: "🍋" },
    { id: 63, name: "Jaljeera", price: 25, category: "beverages", image: "🌿" },
    { id: 64, name: "Ice Tea", price: 60, category: "beverages", image: "🧊" },
    { id: 65, name: "Cold Coffee", price: 80, category: "beverages", image: "🥤" },
    { id: 66, name: "Flavoured Slush", price: 50, category: "beverages", image: "🍧" },
    { id: 67, name: "Milkshakes", price: 80, category: "beverages", image: "🥤" },
    { id: 68, name: "Thickshakes", price: 100, category: "beverages", image: "🥤" },
    { id: 69, name: "Softy", price: 30, category: "sweets", image: "🍦" },
    { id: 70, name: "Fruit Smoothie", price: 90, category: "beverages", image: "🍓" },
    { id: 71, name: "Sugar Cane Juice", price: 30, category: "beverages", image: "🎋" },
    { id: 72, name: "Fruit Bowl", price: 50, category: "healthy", image: "🥗" },
    { id: 73, name: "Healthy Salad Bowls", price: 70, category: "healthy", image: "🥗" },
    { id: 74, name: "Healthy Soups", price: 40, category: "healthy", image: "🍲" },
    { id: 75, name: "Waffles", price: 80, category: "sweets", image: "🧇" },
    { id: 76, name: "Pasta", price: 110, category: "italian", image: "🍝" },
    { id: 77, name: "Garlic Bread", price: 80, category: "italian", image: "🥖" },
    { id: 78, name: "Momos", price: 75, category: "chinese", image: "🥟" },
    { id: 79, name: "Lebanese Food Items", price: 120, category: "italian", image: "🥙" },
    { id: 80, name: "Pastry", price: 80, category: "sweets", image: "🍰" },
    { id: 81, name: "Nachos", price: 80, category: "italian", image: "🧀" }
];